---
- name: configure Fedora workstation
  hosts: localhost
  connection: local
  become: yes
  roles:
    - role: common
    - role: fedora-workstation
      vars:
        workstation_hostname: prime.maballou.com
        workstation_domain: maballou.com
        workstation_dns: 192.168.0.251 192.168.0.252
...
