---
- hosts: localhost 
  vars:
  remote_user: root
  tasks:
  - name: install multiple packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - brasero
      - easytag
      - freeipa-client
      - gnucash
      - google-chrome-stable
      - gparted
      - jnettop
      - keepass
      - simple-scan
      - vim

