---
- hosts: default
  remote_user: root

  vars:
  vars_prompt:
    - name: "ipa_password"
      prompt: "Enter IPA password: "

  tasks:
  - name: Add repository
    yum_repository:
      name: google-chrome
      description: google-chrome
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgcheck: yes
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  - name: install multiple packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - autofs
      - brasero
      - cifs-utils
      - easytag
      - freeipa-client
      - gnucash
      - google-chrome-stable
      - gparted
      - ipa-client
      - jnettop
      - keepass
      - libsss_autofs
      - nfs-utils
      - python2-libselinux
      - python2-libsemanage
      - simple-scan
      - vim
  - name: set SElinux use_nfs_home_dirs
    seboolean:
      name: use_nfs_home_dirs
      state: yes
      persistent: yes
#  - name: enabled NetworkManager-wait-online.service
#    systemd:
#      name: NetworkManager-wait-online.service
#      enabled: yes
  - name: enable autofs
    systemd:
      name: autofs
      enabled: yes
      state: started
  - name: setup FreeIPA
    command: /usr/sbin/ipa-client-install --domain=maballou.com --server=ipa.maballou.com --realm=MABALLOU.COM --fixed-primary --principal admin --password {{ ipa_password }} --force-join --unattended --request-cert
  - name: setup FreeIPA automount
    command: /usr/sbin/ipa-client-automount -U
