---
- hosts: localhost 
  vars:
  remote_user: root
  tasks:
  - name: install packages
    package:
      name: gnucash
      state: present
    package:
      name: vim
      state: present
  - name: install multiple packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - brasero
      - easytag

