---
- hosts: localhost 
  vars:
  remote_user: root
  tasks:
  - name: Add repository
    yum_repository:
      name: google-chrome
      description: google-chrome
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgcheck: yes
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  - name: install multiple packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - autofs
      - brasero
      - easytag
      - freeipa-client
      - gnucash
      - google-chrome-stable
      - gparted
      - jnettop
      - keepass
      - libsss_autofs
      - nfs-utils
      - simple-scan
      - vim
  -name: set SElinux use_nfs_home_dirs
   seboolean:
     name: use_nfs_home_dirs
     state: yes
     persistent: yes
  -name: enabled NetworkManager-wait-online.service
   systemd:
     name: NetworkManager-wait-online.service
     enabled: yes
     started: yes
  -name: enable autofs
   systemd:
     name: autofs
     enabled: yes
     started: yes

