---
- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Print all available facts
      debug:
        var: ansible_facts
    - name: Print a variable
      debug:
#        msg: distribution_version is {{ distribution_version }}
        var: distribution_version
...
