---
- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
  async: 120
  poll: 0
  register: net_restarting

- name: check restart NetworkManager
  async_status:
    jid: "{{ net_restarting.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  listen: restart NetworkManager

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
...
