---
all:
  hosts:
    backups.maballou.com:
    files-1.maballou.com:
    names-1.maballou.com:
    names-2.maballou.com:
    pi-1.maballou.com:
    pi-2.maballou.com:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    centosservers:
      hosts:
        backups.maballou.com:
        files-1.maballou.com:
        names-1.maballou.com:
        names-2.maballou.com:
    backupservers:
      hosts:
        backups.maballou.com:
    directoryservers:
      hosts:
    fileservers:
      hosts:
        files-1.maballou.com:
    nameservers:
      hosts:
        names-1.maballou.com:
        names-2.maballou.com:
    piservers:
      hosts:
        pi-2.maballou.com:
          fltconf_dhcp_start: '192.168.2.2'
          fltconf_dhcp_end: '192.168.2.254'
        pi-3.maballou.com:
          fltconf_dhcp_start: '192.168.3.2'
          fltconf_dhcp_end: '192.168.3.254'
    k8sservers:
      hosts:
        k8s-api-server:
        k8s-master-1:
        k8s-master-2:
        k8s-master-3:
        k8s-node-1:
        k8s-node-2:
        k8s-node-3:
...
