---
# Set timezone and NTP server
- name: Set timezone to US/Central
  timezone:
    name: US/Central

# Update packages
- name: Update packages
  dnf:
    name: '*'
    state: latest

# Enable old CGroups
- name: Check if systemd.unified_cgroup_hierarchy=0 is set in kernelopts
  command: grep -Eq '^kernelopts=.* systemd\.unified_cgroup_hierarchy=0' /boot/grub2/grubenv
  args:
    warn: false
  register: grubenv_has_cgroup_exception
  ignore_errors: yes
  changed_when: no
  failed_when: false
- name: Configure systemd.unified_cgroup_hierarchy=0 in kernelopts
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when:
   - grubenv_has_cgroup_exception.rc != 0
- name: reboot machine
  reboot:
    reboot_timeout: 600
  when:
   - grubenv_has_cgroup_exception.rc != 0

# Check if the Docker repository is installed
- name: Check for Docker repository
  command: dnf config-manager docker-ce-stable --dump
  args:
    warn: false
  register: docker_ce_repository_status
  ignore_errors: yes
  changed_when: no
  failed_when: false

# Add Docker repository
- name: Add Docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false
  changed_when:
    - docker_ce_repository_status.rc != 0

#Install Docker
- name: Install Docker Engine
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

# Enable Docker
- name: Enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

# Add user admin to docker group
- name: Add user admin to docker group
  user:
    name: admin
    groups: docker
    append: yes

# Install firewalld
- name: Install firewalld
  dnf:
    name: firewalld

# Enable firewalld
- name: Enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

# Add DHCP to firewalld
- name: Add DHCP to firewalld
  firewalld:
    service: dhcp
    state: enabled
    immediate: yes
    permanent: yes

# Add DNS to firewalld
- name: Add DNS to firewalld
  firewalld:
    service: dns 
    state: enabled
    immediate: yes
    permanent: yes

# Add HTTP to firewalld
- name: Add HTTP to firewalld
  firewalld:
    service: http
    state: enabled
    immediate: yes
    permanent: yes

# Add masquerade to firewalld so Docker containers can access the Internet
- name: Add masquerade to firewalld so Docker containers can access the Internet
  firewalld:
    masquerade: 'True'
    state: enabled
    permanent: yes
    zone: public

# Install Git
- name: Install Git
  dnf:
    name: git

# Checkout Docker repo
- name: Checkout Docker repo
  git:
    repo: 'https://github.com/mikeblaa/docker.git'
    dest: /opt/docker

# Start Pihole with docker-compose
- name: Create and start services
  docker_compose:
    project_src: /opt/docker/pihole
