---
- name: Populate service facts
  ansible.builtin.service_facts:

# Set timezone and NTP server
- name: Set timezone to US/Central
  timezone:
    name: US/Central

# Update packages
- name: Update packages
  dnf:
    name: '*'
    state: latest

# Install Podman
- name: Install Podman
  dnf:
    name:
      - podman

# Enable Podman
- name: Enable Podman
  systemd:
    name: podman
    state: started
    enabled: yes

# Install firewalld
- name: Install firewalld
  dnf:
    name: firewalld

# Enable firewalld
- name: Enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

# Add DHCP to firewalld
- name: Add DHCP to firewalld
  firewalld:
    service: dhcp
    state: enabled
    immediate: yes
    permanent: yes

# Add DNS to firewalld
- name: Add DNS to firewalld
  firewalld:
    service: dns 
    state: enabled
    immediate: yes
    permanent: yes

# Add HTTP to firewalld
- name: Add HTTP to firewalld
  firewalld:
    service: http
    state: enabled
    immediate: yes
    permanent: yes

# Add masquerade to firewalld so Docker containers can access the Internet
- name: Add masquerade to firewalld so Docker containers can access the Internet
  firewalld:
    masquerade: 'True'
    state: enabled
    permanent: yes
    zone: public

# Install Git
- name: Install Git
  dnf:
    name: git

# Create Pihole container with Podman
- name: Create Pihole container with Podman
  containers.podman.podman_container:
    name: pihole
    image: docker.io/pihole/pihole:2025.08.0
    state: present
    network:
      - "host"
    volumes:
      - "etc-pihole:/etc/pihole:z"
    env:
      TZ: "America/Chicago"
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'
      FTLCONF_webserver_api_password: '{{ webserver_api_password }}'
      FTLCONF_dhcp_start: '{{ fltconf_dhcp_start }}'
      FTLCONF_dhcp_end: '{{ fltconf_dhcp_end }}'
      FTLCONF_dhcp_router: '192.168.1.1'
      FTLCONF_dns_domain: 'maballou.com'
      FTLCONF_dns_revServers: 'true,192.168.0.0/16,192.168.10.1,maballou.com;true,192.168.0.0/16,192.168.10.2,maballou.com'
    cap_add:
      - "NET_ADMIN"
      - "CAP_NET_BIND_SERVICE"
      - "CAP_NET_RAW"
      - "CAP_NET_ADMIN"
      - "CAP_SYS_NICE"
      - "CAP_CHOWN"
      - "CAP_SYS_TIME"
      - "CAP_IPC_LOCK"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    generate_systemd:
      path: /tmp/
      restart_policy: always
      time: 120
      names: yes

#Install python3-libsemanage
- name: Install python3-libsemanage
  dnf:
    name:
      - python3-libsemanage
    state: latest

# Set selinux container_manage_cgroup
- name: Set selinux container_manage_cgroup
  seboolean:
    name: container_manage_cgroup
    state: yes
    persistent: yes

# Copy container-pihole systemd service
- name: Copy container-pihole systemd service
  copy: 
    remote_src: yes
    src: /tmp/container-pihole.service
    dest: /etc/systemd/system/container-pihole.service
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
    mode: '0640'

# Disable and stop systemd-resolved systemd service
- name: Disable and stop systemd-resolved systemd service
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
  when: ansible_facts.services["systemd-resolved.service"] is defined

# Enable and start container-pihole systemd service
- name: Enable and start container-pihole systemd service
  systemd:
    name: container-pihole
    daemon_reload: yes
    enabled: yes
    state: started
...
