---
- name: update packages
  dnf:
    name: '*'
    state: latest

# Create local users until an LDAP is set up
- name: add group mike
  group:
    name: mike
    gid: 10000

- name: add user mike
  user:
    name: mike
    comment: Mike
    uid: 10000
    group: mike
    groups: users,wheel
    password: $6$IzOCD.iKvcFk4OHg$Cs7Sctf2AyLhgOtMLE1618iP0eOyQaoyC2NlSmm3ytlLRtsA82PkWCN0sxYT66Lhw53t0BkQSD9ksK0en4hSF/

- name: install nfs-utils
  dnf:
    name:
      - nfs-utils

- name: systemd automount files
  template: 
    src: files/home-mike.mount 
    dest: /etc/systemd/system/home-mike.mount
    owner: root
    group: root
    mode: '0644'

- name: enabled networkmanager-wait-online.service
  systemd:
    name: NetworkManager-wait-online.service 
    enabled: yes
    state: started

- name: start home-mike automount
  systemd:
    name: home-mike.mount
    enabled: yes
    state: started

- name: install python3-libsemanage
  dnf:
    name:
      - python3-libsemanage

- name: set selinux use_nfs_home_dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes
...
