---
- include_vars: main.yml

- name: set hostname
  hostname:
    name: prime.maballou.com
#  - name: configure networking
#    nmcli:
#      dns4: 192.168.0.1 192.168.0.2
#      dns6: fe80::a4be:aa5f:694d:2c48 fe80::20c:29ff:fee7:7379
#      gw4: 192.168.0.254
#      ip4: 192.168.0.99/24
#      state: present

- name: enable third-party repositories
  dnf:
    name: fedora-workstation-repositories
    state: latest

- name: enable google-chrome repository
  command: dnf config-manager --set-enabled google-chrome
  args:
    warn: false

- name: update packages
  dnf:
    name: '*'
    state: latest

- name: install multiple packages
  dnf:
    name:
      - brasero
      - cifs-utils
      - easytag
      - gnucash
      - google-chrome-stable
      - gparted
      - jnettop
      - keepass
      - libdbi-dbd-sqlite
      - nfs-utils
      - python3-libsemanage
      - simple-scan
      - vim
    state: latest

- name: set selinux cups_execmem 
  seboolean:
    name: cups_execmem
    state: yes
    persistent: yes

- name: set selinux use_nfs_home_dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes

- name: set selinux virt_use_nfs
  seboolean:
    name: virt_use_nfs
    state: yes
    persistent: yes

- name: enabled networkmanager-wait-online.service
  systemd:
    name: NetworkManager-wait-online.service 
    enabled: yes

- name: start SSSD after network-online
  lineinfile:
    path: /lib/systemd/system/sssd.service
    line: 'After=network-online.target'
    insertbefore: Before=.*

- name: systemd automount files
  template: 
    src: "{{ item }}" 
    dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2','') }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
      - templates/mnt-*.j2

- name: start mnt-mike automount
  systemd:
    name: mnt-mike.mount
    enabled: yes
    state: started

- name: start mnt-share automount
  systemd:
    name: mnt-share.mount
    enabled: yes
    state: started

- name: enable sshd
  systemd:
    name: sshd
    enabled: yes
    state: started
...