---
- include_vars: main.yml

- name: set hostname
  hostname:
    name: prime.maballou.com
    use: systemd

- name: install needed network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - policycoreutils-python-utils
    state: present

- name: configure networking
  nmcli:
    conn_name: 'Wired connection 1'
    type: ethernet
    ip4: 192.168.0.99/24
    gw4: 192.168.0.254
    state: present

- name: set local DNS server using systemd-resolved
  lineinfile:
      path: /etc/systemd/resolved.conf
      state: present
      regexp: "^#?DNS=.*"
      line: "DNS=192.168.0.250"
      backup: yes

- name: set local DNS server using systemd-resolved
  lineinfile:
      path: /etc/systemd/resolved.conf
      state: present
      regexp: "^#?Domains=.*"
      line: "Domains=maballou.com"
      backup: yes

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: enable third-party repositories
  dnf:
    name: fedora-workstation-repositories
    state: latest

- name: enable google-chrome repository
  command: dnf config-manager --set-enabled google-chrome
  args:
    warn: false

- name: update packages
  dnf:
    name: '*'
    state: latest

- name: install multiple packages
  dnf:
    name:
      - brasero
      - cifs-utils
      - easytag
      - gnucash
      - google-chrome-stable
      - gparted
      - jnettop
      - keepass
      - libdbi-dbd-sqlite
      - nfs-utils
      - python3-libsemanage
      - simple-scan
      - snapd
      - vim
    state: latest

# Enable classic snap support
- name: Create a symbolic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

# Install Visual Studio Code using snap with classic confinement
- name: Install Visual Studio Code with option --classic
  snap:
    name: code
    classic: yes

- name: install pip packages
  pip:
    name:
      - piecash

- name: fix a bug in piecash
  lineinfile:
      path: /usr/local/lib/python3.9/site-packages/piecash/core/session.py
      state: present
      regexp: "^.*'Gnucash': 300000.*"
      line: "        'Gnucash': 3000001,"
      backup: yes

- name: fix a bug in piecash
  lineinfile:
      path: /usr/local/lib/python3.9/site-packages/piecash/core/session.py
      state: present
      regexp: "^.*'splits':.*"
      line: "        'splits': 5,"
      backup: yes

- name: set selinux cups_execmem 
  seboolean:
    name: cups_execmem
    state: yes
    persistent: yes

- name: set selinux use_nfs_home_dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes

- name: set selinux virt_use_nfs
  seboolean:
    name: virt_use_nfs
    state: yes
    persistent: yes

- name: enabled networkmanager-wait-online.service
  systemd:
    name: NetworkManager-wait-online.service 
    enabled: yes

- name: start SSSD after network-online
  lineinfile:
    path: /lib/systemd/system/sssd.service
    line: 'After=network-online.target'
    insertbefore: Before=.*

- name: systemd automount files
  template: 
    src: "{{ item }}" 
    dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2','') }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
      - templates/mnt-*.j2

- name: start mnt-mike automount
  systemd:
    name: mnt-mike.mount
    enabled: yes
    state: started

- name: start mnt-share automount
  systemd:
    name: mnt-share.mount
    enabled: yes
    state: started

- name: enable sshd
  systemd:
    name: sshd
    enabled: yes
    state: started
...
