---
- name: install centos packages
  dnf:
    name:
      - cockpit
      - open-vm-tools

- name: enabled cockpit
  systemd:
    name: cockpit.socket
    enabled: yes
    state: started

- name: enable chronyd
  systemd:
    name: chronyd.service
    enabled: yes
    state: started
...
